development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d267e42300734140547cd5123601c3d3@crestfish.redistogo.com:11879/
  channel_prefix: instatalk_production
